analytics: {}
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#888888'
    - '#000000'
    - '#000000'
  brandStrength: 0.638068
  lightness: 0.493243
  rhythmicContrast: 0.125553
  saturation: 0.022804
cta: {}
layout_spectrum: 0.244932
name: zeropointaudio
opengraph: {}
purpose: {}
typography_spectrum: 0.219595
