name: zeropointaudio
favicon: null
layout_spectrum: 0.244932
typography_spectrum: 0.219595
title: Zero Point Audio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0C0'
    - '#000000'
    - '#888888'
    - '#000000'
    - '#000000'
  brandStrength: 0.638068
  lightness: 0.493243
  saturation: 0.022804
  rhythmicContrast: 0.125553
purpose:
  - name: null
    item: null
    url: null
